site_name: 🧩 DemoGPT
theme:
    name: dracula
nav:
    - Home: index.md
    - "Value Proposition": values.md
    - "Mission And Vision": mission_and_vision.md
    - Roadmap: roadmap.md
    - Architecture: pipeline.md
    - "Python Interface": python.md
    - Modules: src_plan.md
    - Chains: src_plan_chains.md
    - Prompts: src_plan_chains_prompts.md
    - Tasks: src_plan_chains_prompts_tasks.md
    - Test: test.md