site_name: 🧩 DemoGPT

theme:
    name: material

nav:
    - Home: index.md
    - Modules: 
        - Overview: src_plan.md
        - Chains: 
            - Overview: src_plan_chains.md
            - Prompts: 
                - Overview: src_plan_chains_prompts.md
                - Tasks: src_plan_chains_prompts_tasks.md
    - Test: test.md
